name: CI/CD Pipeline

on:
  push:
    branches:
      - abdallah-ahmed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: echo "Pipeline is working!"
